---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: MODEL_NAME
  name: MODEL_NAME
  namespace: NAMESPACE
spec:
  ports:
  - name: model-serving
    port: 80
    targetPort: "http-server"
  selector:
    app: MODEL_NAME
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: MODEL_NAME
  name: MODEL_NAME-dep
  namespace: NAMESPACE
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: MODEL_NAME
        version: v1
    spec:
      containers:
      - name: MODEL_NAME
        image: IMAGE_NAME
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          tcpSocket:
            port: 8080
        ports:
        - name: http-server
          containerPort: 8080
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 1Gi
